"""
Phase 5 -- Clinical Report Upgrade.

Builds one structured, clinician-oriented "clinical report" per variant
from the canonical `InterpretationResult` dict (Phase 2), including the
confidence (Phase 3) and prioritization (Phase 4) data already attached
to it. Every section below reads a field `InterpretationResult` already
computed -- nothing here re-derives evidence from raw provider dicts a
second time (the one exception, `raw_evidence`, is itself a field
`InterpretationResult` already carries -- see interpretation_result.py),
and nothing is invented that GEPER doesn't actually have.

Single source of truth: both `report/json_builder.py` (adds this dict
as an additive `clinical_report` key) and `report/report_generator.py`
(renders this same dict as Markdown) call `build_clinical_report()` --
so the two output formats can never drift out of sync, per the Phase 5
requirement to "reuse InterpretationResult instead of rebuilding logic
repeatedly."
"""

from typing import Any, Dict, List, Optional

from config import CONFIG
from utils.service_health import HEALTH

# Stable, well-known public-resource references for whichever sources
# actually contributed evidence to this variant (via `evidence_sources`,
# already computed by Phase 2 -- not re-derived here). These are fixed
# citations to the resource itself, not fabricated per-variant claims.
_REFERENCES = {
    "ClinVar": "ClinVar -- https://www.ncbi.nlm.nih.gov/clinvar/",
    "dbSNP": "dbSNP -- https://www.ncbi.nlm.nih.gov/snp/",
    "gnomAD": "gnomAD -- https://gnomad.broadinstitute.org/",
    "ClinGen": "ClinGen -- https://clinicalgenome.org/",
    "UniProt": "UniProt -- https://www.uniprot.org/",
    "InterPro": "InterPro/Pfam -- https://www.ebi.ac.uk/interpro/",
    "AlphaFold DB": "AlphaFold Protein Structure Database -- https://alphafold.ebi.ac.uk/",
    "AlphaMissense": "AlphaMissense -- Cheng et al. 2023, Science (DeepMind/AlphaMissense)",
    "MMSplice": "MMSplice -- Cheng et al. 2019, Genome Biology",
    "BLAST": "NCBI BLAST -- https://blast.ncbi.nlm.nih.gov/",
    "protein_translator": "GEPER internal reference/alternate protein translation (standard genetic code).",
}

_TOOL_LIMITATIONS = (
    "This report is generated by an automated research pipeline combining public database "
    "lookups, curated clinical resources, and machine-learning predictors. It is not a "
    "substitute for professional clinical genetic interpretation, diagnosis, or advice, and "
    "should be reviewed by a qualified clinical geneticist or genetic counselor before any "
    "medical decision is made.",
    "Protein-residue positions used for domain (InterPro/Pfam) and structural (AlphaFold DB) "
    "overlap checks are estimates derived from the variant's coding-sequence position, not "
    "transcript-verified coordinates; treat domain/structure overlap findings as supportive, "
    "not definitive.",
    "Sequence-context models (HyenaDNA, Evo2, RNA-FM, ESM2) contribute routing and "
    "embedding context in this pipeline; they do not themselves output a per-variant "
    "pathogenic/benign verdict, and are reported separately from AlphaMissense/MMSplice for "
    "that reason.",
)


def build_clinical_report(
    interpretation_result: Optional[Dict[str, Any]],
    variant_dict: Dict[str, Any] = None,
    raw_evidence: Optional[Dict[str, Any]] = None,
    indigenomes_result: Optional[Dict[str, Any]] = None,
    thousand_genomes_sas_result: Optional[Dict[str, Any]] = None,
) -> Optional[Dict[str, Any]]:
    """
    Returns the 17-section clinical report dict, or `None` if
    `interpretation_result` is missing/errored (e.g. the aggregation
    engine failed for this variant) -- callers must not fabricate a
    report when the underlying data isn't there.

    `raw_evidence`: the raw per-stage provider dicts (uniprot, interpro,
    alphafold, gnomad, dbsnp, clinvar, clingen, blast, ...) this
    variant's evidence-dependent sections (protein/structural/
    population/clinical knowledge, sequence context) are built from.

    Pass this explicitly whenever the caller has the live provider
    dicts in hand (as `report/json_builder.py::build_variant_result`
    now does -- see that module) rather than relying on
    `interpretation_result["raw_evidence"]`: `InterpretationResult
    .to_dict()` (`pipeline/interpretation_result.py`) deliberately
    OMITS `raw_evidence` from its serialized output (to avoid
    duplicating data already emitted under the top-level `uniprot`/
    `interpro`/`gnomad`/etc. keys), so `interpretation_result` here --
    which is that *serialized* dict, not the live dataclass instance --
    never actually carries it. Before this parameter existed, every
    caller silently fell through to `ir.get("raw_evidence") or {}`,
    which was *always* an empty dict, so every one of this function's
    raw-evidence-derived sections (protein/structural/population/
    clinical knowledge, sequence context) unconditionally reported
    "not found"/"no annotation available" regardless of what the
    corresponding stage had actually returned -- a real bug (found via
    a live Colab run where the report claimed "UniProt: no entry
    resolved" in this section while the same report's own Annotation
    Detail trail, built from the actual stage output, showed a
    resolved accession two sections later). Kept optional and
    falling back to the old (broken-if-empty) behavior only so this
    isn't a breaking API change for any other future caller.

    `indigenomes_result`: the raw IndiGenomes provider dict (see
    `annotation/indigenomes.py::IndiGenomesLookup.query_variant`) for
    the `indian_population_frequency` section below. Passed as its own
    explicit parameter, NOT folded into `raw_evidence` -- that dict's
    validated shape (`pipeline/stage_schemas.py::RawEvidenceBundle`)
    has a fixed 11 fields and IndiGenomes is not one of them (an India-
    deployment-only source, unlike gnomAD/ClinVar/etc.); adding an
    unlisted key there would raise a `TypeError` at the schema
    boundary rather than degrade gracefully.

    `thousand_genomes_sas_result`: the raw 1000 Genomes SAS fallback
    provider dict (see `annotation/thousand_genomes_sas.py
    ::ThousandGenomesSASLookup.query_variant`), same reasoning as
    `indigenomes_result` for why it's a separate explicit parameter.
    Only ever shown in the report when IndiGenomes was confirmed
    offline this run -- see `_indian_population_frequency` below.
    """
    if not interpretation_result or "error" in interpretation_result:
        return None
    ir = interpretation_result
    raw = raw_evidence if raw_evidence is not None else (ir.get("raw_evidence") or {})

    return {
        "executive_summary": _executive_summary(ir, variant_dict),
        "acmg_classification": _acmg_section(ir),
        "confidence": _confidence_section(ir),
        "priority": _priority_section(ir),
        "supporting_evidence": ir.get("supporting_evidence", []),
        "conflicting_evidence": _conflicting_evidence(ir),
        "conflict_resolution": _conflict_resolution_section(ir),
        "explainability": ir.get("explainability"),
        "ai_consensus": _ai_consensus_section(ir),
        "protein_knowledge": _protein_knowledge(raw),
        "structural_knowledge": _structural_knowledge(raw),
        "population_evidence": _population_evidence(raw),
        "indian_population_frequency": _indian_population_frequency(
            raw, indigenomes_result, thousand_genomes_sas_result
        ),
        "clinical_evidence": _clinical_evidence(raw),
        "sequence_context": _sequence_context(ir, raw),
        "recommendations": ir.get("recommendations", []),
        "limitations": _limitations(ir),
        "references": _references(ir),
        "evidence_sources": ir.get("evidence_sources", []),
    }


# ----------------------------------------------------------------------
# Section builders. Each reads only fields InterpretationResult already
# computed (Phase 1-4) -- no new scoring, classification, or evidence
# derivation happens here.
# ----------------------------------------------------------------------


def _executive_summary(ir: Dict[str, Any], variant_dict: Dict[str, Any] = None) -> str:
    variant_dict = variant_dict or ir.get("variant") or {}
    locus = f"{variant_dict.get('chrom')}:{variant_dict.get('pos')} {variant_dict.get('ref')}>{variant_dict.get('alt')}"
    gene = ir.get("gene_symbol")
    gene_clause = f" in {gene}" if gene else ""

    classification = ir.get("acmg_classification") or "not classified"
    conf_label = ir.get("confidence_label")
    conf_clause = (
        f" (confidence: {conf_label})"
        if conf_label and not ir.get("confidence_pending", True)
        else " (confidence not yet scored)"
    )

    priority_cat = ir.get("priority_category")
    priority_clause = (
        f" Assigned {priority_cat} review priority." if priority_cat and not ir.get("priority_pending", True) else ""
    )

    n_triggered = len(ir.get("triggered_rules", []))
    n_not_evaluated = len(ir.get("not_evaluated_rules", []))
    evidence_clause = (
        f" {n_triggered} ACMG criteria were triggered by available evidence"
        f"{f'; {n_not_evaluated} could not be evaluated due to missing data sources' if n_not_evaluated else ''}."
    )

    return (
        f"Variant {locus}{gene_clause} was classified as **{classification}**{conf_clause}."
        f"{priority_clause}{evidence_clause}"
    )


def _acmg_section(ir: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "classification": ir.get("acmg_classification"),
        "triggered_criteria": [
            {
                "code": c.get("code"),
                "strength": c.get("strength"),
                "direction": c.get("direction"),
                "rationale": c.get("rationale"),
            }
            for c in ir.get("triggered_rules", [])
        ],
        "combining_rule_trace": ir.get("combining_rule_trace", []),
        "not_evaluated_count": len(ir.get("not_evaluated_rules", [])),
    }


def _confidence_section(ir: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "pending": ir.get("confidence_pending", True),
        "score": ir.get("confidence_score"),
        "label": ir.get("confidence_label"),
        "breakdown": ir.get("confidence_breakdown"),
    }


def _priority_section(ir: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "pending": ir.get("priority_pending", True),
        "score": ir.get("priority_score"),
        "category": ir.get("priority_category"),
        "rank": ir.get("priority_rank"),
        "explanation": ir.get("priority_explanation", []),
        "breakdown": ir.get("priority_breakdown"),
    }


def _conflicting_evidence(ir: Dict[str, Any]) -> List[str]:
    conflicts = ir.get("conflicting_evidence", [])
    return conflicts  # already a deduped, sourced list from Phase 2; empty list if none -- never fabricated


def _conflict_resolution_section(ir: Dict[str, Any]) -> Dict[str, Any]:
    # Phase 6, added as a new top-level section rather than changing the
    # shape of the existing `conflicting_evidence` key above (which
    # Phase 5 already shipped as a plain list) -- keeps that key
    # backward compatible while still surfacing the richer, resolved
    # conflict data from the Conflict Resolution Engine.
    return {
        "summary": ir.get("conflict_summary"),
        "score": ir.get("conflict_score"),
        "severity": ir.get("conflict_severity"),
        "resolution": ir.get("conflict_resolution"),
        "conflicts": ir.get("conflict_list", []),
    }


def _ai_consensus_section(ir: Dict[str, Any]) -> Dict[str, Any]:
    """
    `model_errors` distinguishes "this model genuinely crashed" from
    "this model was never applicable/available" -- an absent entry in
    `classifying_models` alone is ambiguous between the two (a
    synonymous variant never routed to AlphaMissense looks identical
    to an AlphaMissense that crashed, from `classifying_models` alone).
    Same distinction `_protein_knowledge`/`_structural_knowledge`/
    `_clinical_evidence`'s `*_error` fields already make for UniProt/
    InterPro/AlphaFold/ClinVar/ClinGen -- see
    `pipeline/interpretation_result.py::InterpretationResult
    .ai_model_errors`'s docstring for where this is computed.
    """
    return {
        "classifying_models": ir.get("ai_consensus", []),  # AlphaMissense / MMSplice verdicts only
        "context_models_used": ir.get("ai_context_models", []),  # HyenaDNA/Evo2/RNA-FM/ESM2, no verdict
        "model_errors": ir.get("ai_model_errors", []),
    }


def _protein_knowledge(raw: Dict[str, Any]) -> Dict[str, Any]:
    """
    `uniprot_error`/`interpro_error` are surfaced as their own field,
    distinct from `*_available` -- a failed external lookup (e.g. the
    EBI InterPro API returning an error after retries) is not the same
    statement as "this protein genuinely has no annotation", and
    conflating the two would misreport an external-service outage as a
    negative biological finding. Matches the distinction
    `report/report_generator.py::_render_uniprot`/`_render_interpro`
    (the Annotation Detail audit trail) already make for the same
    provider dicts -- this brings the Clinical Interpretation Report's
    summary section into agreement with it.
    """
    uniprot = raw.get("uniprot") or {}
    interpro = raw.get("interpro") or {}
    out: Dict[str, Any] = {
        "uniprot_available": False,
        "uniprot_error": uniprot.get("error"),
        "interpro_available": False,
        "interpro_error": interpro.get("error"),
    }
    if uniprot.get("found"):
        out["uniprot_available"] = True
        out["uniprot"] = {
            "accession": uniprot.get("accession"),
            "protein_name": uniprot.get("protein_name"),
            "reviewed": uniprot.get("reviewed"),
        }
    if interpro.get("found"):
        out["interpro_available"] = True
        out["interpro"] = {
            "protein_position": interpro.get("protein_position"),
            # `affected_domains` stays three-valued here too (None =
            # position unknown, domain overlap never checked; [] =
            # checked, no overlap; non-empty = overlap found) -- see
            # `pipeline/interpro/lookup.py::query_variant`'s
            # docstring. `.get(..., [])`'s default only applies when
            # the key is absent, so an explicit `None` value passes
            # through unchanged rather than being silently coerced.
            "affected_domains": interpro.get("affected_domains", []),
            "domain_overlap": bool(interpro.get("affected_domains")),
        }
    return out


def _structural_knowledge(raw: Dict[str, Any]) -> Dict[str, Any]:
    """`error` distinguishes a failed AlphaFold DB lookup from a
    genuine "no structure resolved" result -- see `_protein_knowledge`'s
    docstring for the same distinction and why it matters."""
    alphafold = raw.get("alphafold") or {}
    if not alphafold.get("found"):
        return {"available": False, "error": alphafold.get("error")}
    # `confidence_band`/`confidence_band_is_residue_specific` distinguish
    # "pLDDT at this variant's own residue" from a silent fallback to
    # the whole-protein mean when the residue position is unknown --
    # both are legitimate numbers, but reporting one under a label that
    # doesn't say which would let a reader assume residue-specificity
    # that isn't there.
    residue_band = alphafold.get("affected_residue_band")
    return {
        "available": True,
        "confidence_band": residue_band or alphafold.get("mean_plddt_band"),
        "confidence_band_is_residue_specific": residue_band is not None,
        "protein_position": alphafold.get("protein_position"),
        "mean_plddt": alphafold.get("mean_plddt"),
        "affected_residue_plddt": alphafold.get("affected_residue_plddt"),
        "model_version": alphafold.get("model_version"),
        "pdb_url": alphafold.get("pdb_url"),
        "cif_url": alphafold.get("cif_url"),
        "protein_position_basis": alphafold.get("protein_position_basis"),
    }


def _population_evidence(raw: Dict[str, Any]) -> Dict[str, Any]:
    gnomad = raw.get("gnomad") or {}
    dbsnp = raw.get("dbsnp") or {}
    return {
        "gnomad": {
            "queried": not (gnomad.get("skipped") or gnomad.get("error")),
            "found": bool(gnomad.get("found")),
            "global_af": gnomad.get("global_af"),
        },
        "dbsnp": {
            "found": bool(dbsnp.get("found")),
            "rsid": dbsnp.get("rsid") if dbsnp.get("found") else None,
        },
    }


def _indian_population_frequency(
    raw: Dict[str, Any],
    indigenomes_result: Optional[Dict[str, Any]],
    thousand_genomes_sas_result: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """
    India-deployment feature: gnomAD's South Asian (SAS) subpopulation
    allele frequency alongside IndiGenomes' own India-specific cohort
    frequency (~1000+ genomes -- see `annotation/indigenomes.py`'s
    module docstring for why this is a live per-variant query, not a
    downloaded index), plus a single "common in Indian populations"
    flag when either exceeds `CONFIG.indigenomes.COMMON_AF_THRESHOLD`
    (default 1%).

    The two figures are reported side by side, never merged into one
    blended number -- they measure genuinely different cohorts
    (gnomAD's global SAS reference population vs. IndiGenomes' India-
    resident cohort) and a reviewer comparing a variant against
    Indian-population background frequency should see both distinctly,
    not a single number this pipeline invented by averaging or
    preferring one over the other.

    `gnomad_af_sas` is read from `raw["gnomad"]["population_breakdown"]`
    (already computed by the gnomAD stage -- see
    `pipeline/gnomad/models.py::POPULATIONS`), not re-queried here.
    `indigenomes_*` distinguishes "not found" (`indigenomes_available
    =False`, `indigenomes_error=None`) from a genuine query failure
    (`indigenomes_error` set, `indigenomes_offline=False`) from a
    skipped-because-confirmed-offline run (`indigenomes_error` set
    *and* `indigenomes_offline=True`, per `utils/service_health.py`'s
    HEALTH registry) and from the integration being disabled/
    GRCh37-skipped (`indigenomes_skipped_reason` set) -- the same
    found-vs-error distinction `_protein_knowledge`'s docstring
    documents for UniProt/InterPro, applied here for the same reason.

    1000 Genomes SAS FALLBACK (`fallback_*` keys)
    -------------------------------------------------------------------
    Surfaced ONLY when `indigenomes_offline` is True -- the same
    condition `pipeline/orchestrator.py::_run_thousand_genomes_sas_stage`
    itself gates the live Ensembl query on, so this is this layer's own
    independent confirmation of the identical signal, not a second
    decision that could drift from it. If IndiGenomes was genuinely
    queried this run (found a record OR confirmed not found), the
    fallback is never shown -- even if `thousand_genomes_sas_result`
    happens to carry usable data -- because a working IndiGenomes
    result must never be cluttered with an inferior backup source (see
    `annotation/thousand_genomes_sas.py`'s module docstring for exactly
    why it's inferior: n=494 total vs. IndiGenomes' 1000+, and diaspora
    samples collected outside India, not India-resident individuals).

    `fallback_population_labels`/`fallback_sample_sizes`/
    `fallback_total_sample_size` are carried through explicitly (not
    left for the renderer to hardcode or, worse, omit) so every render
    of this fallback -- Markdown and both PDF paths -- states both
    mandatory disclosures the same way, from the same source of truth.
    Deliberately NOT folded into `common_in_indian_population` below:
    that flag stays driven by gnomAD SAS + IndiGenomes only, the two
    sources this feature was built to compare -- mixing in a small,
    diaspora-sourced fallback figure would let a genuinely
    low-confidence number quietly influence a clinical flag.
    """
    gnomad = raw.get("gnomad") or {}
    gnomad_sas = (gnomad.get("population_breakdown") or {}).get("sas") or {}
    gnomad_sas_af = gnomad_sas.get("af")

    indigenomes = indigenomes_result or {}
    indigenomes_available = bool(indigenomes.get("found"))
    indigenomes_af = indigenomes.get("af") if indigenomes_available else None

    # Distinguishes "queried, no record" from "skipped this run because
    # IndiGenomes was confirmed offline at startup" (see
    # `utils/service_health.py`) -- the two must never look identical
    # in a report a clinician might rely on. `indigenomes_error` alone
    # can't tell them apart (both surface as an error string), so this
    # cross-checks the run-level HEALTH registry rather than
    # string-matching the error text.
    indigenomes_offline = bool(indigenomes.get("error")) and HEALTH.is_offline("IndiGenomes")

    threshold = CONFIG.indigenomes.COMMON_AF_THRESHOLD
    common_in_indian_population = any(af is not None and af >= threshold for af in (gnomad_sas_af, indigenomes_af))

    tgs = thousand_genomes_sas_result or {}
    fallback_shown = indigenomes_offline
    fallback_available = fallback_shown and bool(tgs.get("found"))

    return {
        "gnomad_af_sas": gnomad_sas_af,
        "gnomad_sas_queried": not (gnomad.get("skipped") or gnomad.get("error")),
        "indigenomes_available": indigenomes_available,
        "indigenomes_af": indigenomes_af,
        "indigenomes_ac": indigenomes.get("ac") if indigenomes_available else None,
        "indigenomes_an": indigenomes.get("an") if indigenomes_available else None,
        "indigenomes_error": indigenomes.get("error"),
        "indigenomes_offline": indigenomes_offline,
        "indigenomes_skipped_reason": indigenomes.get("reason") if indigenomes.get("skipped") else None,
        "common_af_threshold": threshold,
        "common_in_indian_population": common_in_indian_population,
        "fallback_shown": fallback_shown,
        "fallback_available": fallback_available,
        "fallback_error": tgs.get("error") if fallback_shown else None,
        "fallback_rsid": tgs.get("rsid") if fallback_shown else None,
        "fallback_sas_pooled": tgs.get("sas_pooled") if fallback_available else None,
        "fallback_sub_populations": tgs.get("sub_populations") if fallback_available else None,
        "fallback_population_labels": tgs.get("population_labels") if fallback_available else None,
        "fallback_sample_sizes": tgs.get("sample_sizes") if fallback_available else None,
        "fallback_total_sample_size": tgs.get("total_sample_size") if fallback_available else None,
    }


def _clinical_evidence(raw: Dict[str, Any]) -> Dict[str, Any]:
    """`clinvar_error`/`clingen_error` distinguish a failed lookup from
    a genuine "no record"/"no curation" result -- see `_protein_knowledge`'s
    docstring for the same distinction and why it matters."""
    clinvar = raw.get("clinvar") or {}
    clingen = raw.get("clingen") or {}
    out: Dict[str, Any] = {
        "clinvar_available": False,
        "clinvar_error": clinvar.get("error"),
        "clingen_available": False,
        "clingen_error": clingen.get("error"),
    }
    # `primary_record`, never `records[0]` -- ClinVar's positional
    # search can return several distinct co-located variants at one
    # locus, and a bare first-record read used to attribute whichever
    # one sorted first to this variant regardless of whether it was
    # actually the same allele (see `database/clinvar_client.py`'s
    # module docstring for the real case this fixes). `match_status ==
    # "position_only"` means other, non-matching variants exist at
    # this position -- surfaced as count-only context, distinct from
    # "no record found" (`not_found`).
    if clinvar.get("match_status") == "matched" and clinvar.get("primary_record"):
        primary = clinvar["primary_record"]
        out["clinvar_available"] = True
        out["clinvar"] = {
            "clinical_significance": primary.get("clinical_significance"),
            "review_status": primary.get("review_status"),
        }
    elif clinvar.get("match_status") == "position_only":
        out["clinvar_co_located_count"] = len(clinvar.get("records") or [])
    if clingen.get("found"):
        out["clingen_available"] = True
        out["clingen"] = {
            "gene_symbol": clingen.get("gene_symbol"),
            "clinical_validity_summary": clingen.get("clinical_validity_summary"),
            "dosage_sensitivity": clingen.get("dosage_sensitivity"),
        }
    return out


def _sequence_context(ir: Dict[str, Any], raw: Dict[str, Any]) -> Dict[str, Any]:
    """
    `blast["error"]` distinguishes a failed BLAST search from a
    genuine "no homology hits" result -- see `_protein_knowledge`'s
    docstring for the same distinction elsewhere. Unlike UniProt/
    InterPro/AlphaFold/ClinVar/ClinGen, BLAST previously had NO
    mechanism anywhere in this report to make that distinction (see
    `pipeline/orchestrator.py::_run_blast_stage`).
    """
    blast = raw.get("blast") or {}
    return {
        "context_models_used": ir.get("ai_context_models", []),
        "blast": {
            "hit_count": blast.get("hit_count", 0),
            "error": blast.get("error"),
        },
        # Ensembl is used internally for sequence-context retrieval
        # (transcript/region lookups feeding the DNA/RNA models above)
        # rather than surfaced as its own per-variant evidence dict, so
        # it is noted here descriptively rather than scored -- same
        # treatment as in the Phase 3/4 engines.
        "ensembl_note": (
            "Ensembl contributes indirectly via sequence-context retrieval (transcript/region "
            "lookups feeding the sequence-context models above); it is not surfaced as a separate "
            "per-variant evidence source in this pipeline."
        ),
    }


def _limitations(ir: Dict[str, Any]) -> List[str]:
    limitations = list(_TOOL_LIMITATIONS)
    not_evaluated = ir.get("not_evaluated_rules", [])
    if not_evaluated:
        codes = ", ".join(c.get("code", "?") for c in not_evaluated)
        limitations.append(
            f"{len(not_evaluated)} ACMG criteria could not be evaluated for this variant due to "
            f"missing evidence sources ({codes}); see the ACMG classification section for the "
            f"specific reason each was skipped."
        )
    if ir.get("confidence_pending", True):
        limitations.append("Confidence scoring did not complete for this variant.")
    if ir.get("priority_pending", True):
        limitations.append("Priority scoring did not complete for this variant.")
    return limitations


def _references(ir: Dict[str, Any]) -> List[str]:
    sources = ir.get("evidence_sources", [])
    return [_REFERENCES[s] for s in sources if s in _REFERENCES]
