"""
pipeline/reporting/component_identity.py
─────────────────────────────────────────
What this tree calls itself -- the ONE definition, shared by the reports
(pipeline/reporting/stage.py re-exports PIPELINE_VERSION for the JSON, HTML
and PDF; clinical_sections.py re-exports SCOPE_LINE) and every non-report
surface that names this component: the CLIs (main.py, the runner, serve_api.py),
the API's OpenAPI identity, and the environment/dependency checks.

Ruled by the human 2026-09-11 (Option B): this tree is a COMPONENT of Bij AI,
not the whole product -- "the version field must name the same thing the
scope line does." Kept in a module with no imports so `main.py --version`
and `--help` can read it without pulling in the reporting stage's
dependencies.
"""

COMPONENT_NAME = "Bij AI sequencing-analysis component"

# Kim's version -- the ONLY place the number is written (human-approved
# 2026-09-11: "make 8 Kim's single version source"). A plain string literal on
# purpose: setuptools reads it statically for the package metadata
# (pyproject.toml [tool.setuptools.dynamic]) without importing anything.
# Every other surface derives from it: the label below (reports, CLI), the
# API's OpenAPI version and /health, and pipeline.__version__.
VERSION = "8.0.0"
PIPELINE_VERSION = f"{COMPONENT_NAME} v{VERSION.split('.')[0]}"

# Ratified wording (2026-09-11, Option B): what this tree is, said on every
# report (HTML via stage.py, PDF via pdf_report.py) and, verbatim, in
# main.py --help. Clinician-facing text -- change only with human sign-off.
SCOPE_LINE = (
    "Sequencing analysis from FASTQ — produced by the Bij AI sequencing-analysis "
    "component (Kim): QC, alignment and variant calling, with ACMG classification "
    "of the variants called here."
)

# The EJ-01 intended-use disclaimer -- the ONE Kim definition, used by the
# HTML footer (stage.py) and as the PDF footer default (pdf_report.py).
# Ruled by the human (Option 1): Kim adopts GEPER's text BYTE FOR BYTE --
# geper/report/clinical_report_builder.py::RESEARCH_USE_DISCLAIMER. The two
# trees cannot import each other, so this is a copy, and
# tests/test_ej01_disclaimer_cross_tree_drift.py renders both trees' real
# reports in separate processes and fails if they differ. Change BOTH
# together, and only with human sign-off: clinician-facing text.
#
# Plain prose, deliberately: no markup, no leading label. Each renderer
# applies its own wrapper.
#
# UPDATED 2026-09-13 (W116, human ruling): opening clause is now "an
# automated pipeline", not "an automated research pipeline" -- the
# product is sold for clinical use under a clinical sign-off, so the old
# opening named a regulatory category the deployment contradicts. GEPER's
# copy changed in the same commit; nothing else in the sentence moved.
# The name still says RESEARCH_USE: legacy, kept on purpose, and not a
# description of what the text now claims. See the same note on GEPER's
# constant for why it was not renamed.
RESEARCH_USE_DISCLAIMER = (
    "This report is generated by an automated pipeline combining public database "
    "lookups, curated clinical resources, and machine-learning predictors. Bij AI is a variant "
    "prioritisation system that assists qualified clinicians and pathologists. It produces a "
    "draft classification requiring qualified human review and final sign-off before any "
    "clinical use. It does not independently provide final clinical interpretation. It is not "
    "a substitute for professional clinical genetic interpretation, diagnosis, or advice."
)
