"""
pipeline/reporting/pdf_report.py
──────────────────────────────────
ReportLab-based clinical PDF report (Issue 3).

Built natively from the same structured data ReportingStage already
assembles for the HTML/JSON reports (patient metadata, QC summary,
variant dashboard, merged variant+ACMG rows, clinical interpretation) —
NOT by converting the HTML to PDF. This is deliberately independent of
WeasyPrint/wkhtmltopdf (both external, non-pure-Python, and already the
`_try_render_pdf` fallback path in stage.py): ReportLab is a pure-Python
library with no system dependency, so this path is the primary,
most-reliable PDF generator; the WeasyPrint/wkhtmltopdf path in
stage.py is kept only as a secondary fallback for the rare case
ReportLab itself is unavailable.

Nothing here touches alignment, variant calling, annotation, or ACMG
logic — it only renders already-computed dicts (the exact same ones
pipeline/reporting/clinical_sections.py builds for the HTML report).
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from pipeline.reporting.clinical_sections import consequence_display_label

logger = logging.getLogger("geper.pipeline.reporting.pdf_report")


# ACMG classification -> reportlab color, keyed identically to
# pipeline/reporting/stage.py::ACMG_CLASS_STYLES so HTML and PDF never
# disagree on which color means which tier.
def _acmg_class_colors():
    from reportlab.lib import colors

    return {
        "Pathogenic": colors.HexColor("#f8d7da"),
        "Likely_Pathogenic": colors.HexColor("#ffe8cc"),
        "Uncertain_Significance": colors.HexColor("#fff3cd"),
        "Likely_Benign": colors.HexColor("#cfe2ff"),
        "Benign": colors.HexColor("#d1e7dd"),
    }


_QC_STATUS_COLOR_HEX = {
    "PASS": "#155724",
    "WARNING": "#856404",
    "FAIL": "#721c24",
    "UNKNOWN": "#555555",
}


class ReportLabUnavailableError(RuntimeError):
    """Raised when the `reportlab` package cannot be imported. Callers
    (stage.py) catch this and fall back to the WeasyPrint/wkhtmltopdf
    path — PDF generation must never crash the pipeline."""


def render_clinical_pdf(
    pdf_path: str,
    *,
    sample_id: str,
    patient_meta: Dict[str, Any],
    qc_rows: List[Dict[str, Any]],
    dashboard: Dict[str, Any],
    interpretation: Dict[str, str],
    merged_variants: List[Dict[str, Any]],
    ancestry_summary: Optional[str] = None,
    reference_genome: str = "N/A",
    pipeline_version: str = "Bij AI",
    generated_at: Optional[str] = None,
    lab_disclaimer: Optional[str] = None,
    codon_resolution_disclaimer: Optional[str] = None,
) -> str:
    """Render the full clinical PDF report to `pdf_path` and return it.

    Raises ReportLabUnavailableError if reportlab isn't importable, so
    the caller can fall back cleanly. Any other failure (a malformed
    input field, etc.) is caught internally per-section where
    reasonable, but a genuinely fatal layout error will propagate —
    stage.py's own try/except around PDF generation is the safety net
    for "never crash the pipeline over a PDF."
    """
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.platypus import (
            SimpleDocTemplate,
            Paragraph,
            Spacer,
            Table,
            TableStyle,
            PageBreak,
        )
        from reportlab.pdfgen import canvas as reportlab_canvas
    except ImportError as exc:
        raise ReportLabUnavailableError(str(exc)) from exc

    generated_at = generated_at or datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lab_disclaimer = lab_disclaimer or (
        "This report is generated by Bij AI, an in-development bioinformatics pipeline "
        "that assists qualified clinicians and pathologists. It produces a draft "
        "classification requiring qualified human review and final sign-off before "
        "any clinical use, and does not independently provide final clinical "
        "interpretation."
    )
    class_colors = _acmg_class_colors()

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ClinicalTitle",
        parent=styles["Title"],
        fontSize=18,
        textColor=colors.HexColor("#1a4a8a"),
    )
    section_style = ParagraphStyle(
        "ClinicalSection",
        parent=styles["Heading2"],
        fontSize=13,
        textColor=colors.HexColor("#2a6ab5"),
        spaceBefore=14,
        spaceAfter=6,
    )
    body_style = ParagraphStyle("ClinicalBody", parent=styles["Normal"], fontSize=9.5, leading=13)
    small_style = ParagraphStyle(
        "ClinicalSmall", parent=styles["Normal"], fontSize=8, textColor=colors.grey
    )

    story: List[Any] = []

    # ── Header / patient banner ──
    story.append(Paragraph(f"{pipeline_version} — Clinical Genomic Report", title_style))
    # WHAT THIS REPORT IS. Both trees in this repository render a "Clinical
    # Genomic Report" under the same brand, so either one alone reads as the
    # whole product. This names what produced THIS one and what it started from.
    story.append(
        Paragraph(
            "Sequencing analysis from FASTQ — produced by the Kim pipeline: QC, alignment and variant calling, with ACMG classification of the variants called here.",
            body_style,
        )
    )
    story.append(Spacer(1, 4))
    patient_table_data = [
        ["Sample ID", sample_id, "Patient Name", patient_meta.get("name", "")],
        ["Date of Birth", patient_meta.get("dob", ""), "Sex", patient_meta.get("sex", "")],
        ["Ordering Physician", patient_meta.get("physician", ""), "Report Generated", generated_at],
    ]
    patient_table = Table(patient_table_data, colWidths=[100, 150, 100, 150])
    patient_table.setStyle(
        TableStyle(
            [
                ("FONTSIZE", (0, 0), (-1, -1), 8.5),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
                ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#dddddd")),
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f5f8ff")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    story.append(patient_table)
    if patient_meta.get("is_deidentified"):
        story.append(Spacer(1, 3))
        story.append(
            Paragraph(
                "<i>No patient-identifying metadata was supplied for this run — "
                "sample is treated as de-identified / research use.</i>",
                small_style,
            )
        )

    # ── QC summary ──
    story.append(Paragraph("Sequencing QC Summary", section_style))
    qc_table_data = [["Metric", "Value", "Status"]]
    qc_row_colors = [colors.white]
    for row in qc_rows:
        qc_table_data.append([row["label"], row["value"], row["status"]])
        qc_row_colors.append(colors.HexColor(_QC_STATUS_COLOR_HEX.get(row["status"], "#555555")))
    qc_table = Table(qc_table_data, colWidths=[150, 150, 100])
    qc_style_cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2a6ab5")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cccccc")),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]
    for i, color in enumerate(qc_row_colors[1:], start=1):
        qc_style_cmds.append(("TEXTCOLOR", (2, i), (2, i), color))
        qc_style_cmds.append(("FONTNAME", (2, i), (2, i), "Helvetica-Bold"))
    qc_table.setStyle(TableStyle(qc_style_cmds))
    story.append(qc_table)

    # ── Variant summary dashboard ──
    story.append(Paragraph("Variant Summary Dashboard", section_style))
    dash_data = [
        ["Total Classified", "Pathogenic", "Likely Pathogenic", "VUS", "Likely Benign", "Benign"],
        [
            str(dashboard.get("total_variants", 0)),
            str(dashboard.get("pathogenic", 0)),
            str(dashboard.get("likely_pathogenic", 0)),
            str(dashboard.get("vus", 0)),
            str(dashboard.get("likely_benign", 0)),
            str(dashboard.get("benign", 0)),
        ],
    ]
    dash_table = Table(dash_data, colWidths=[80] * 6)
    dash_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2a6ab5")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cccccc")),
                ("BACKGROUND", (1, 1), (1, 1), class_colors["Pathogenic"]),
                ("BACKGROUND", (2, 1), (2, 1), class_colors["Likely_Pathogenic"]),
                ("BACKGROUND", (3, 1), (3, 1), class_colors["Uncertain_Significance"]),
                ("BACKGROUND", (4, 1), (4, 1), class_colors["Likely_Benign"]),
                ("BACKGROUND", (5, 1), (5, 1), class_colors["Benign"]),
            ]
        )
    )
    story.append(dash_table)
    story.append(Spacer(1, 4))
    story.append(
        Paragraph(
            f"<b>Ancestry:</b> {ancestry_summary or dashboard.get('ancestry_summary', 'Not performed')}",
            body_style,
        )
    )

    # ── Clinical interpretation ──
    story.append(Paragraph("Clinical Interpretation", section_style))
    story.append(Paragraph(interpretation.get("summary", ""), body_style))
    story.append(Spacer(1, 4))
    story.append(Paragraph("<b>Recommended Follow-up:</b>", body_style))
    story.append(Paragraph(interpretation.get("follow_up", ""), body_style))

    # ── Variant table ──
    story.append(PageBreak())
    story.append(Paragraph("Variant Detail", section_style))
    if codon_resolution_disclaimer:
        story.append(Paragraph(codon_resolution_disclaimer, small_style))
        story.append(Spacer(1, 4))
    if merged_variants:
        headers = ["Gene", "Transcript", "HGVS", "Consequence", "Classification", "gnomAD AF"]
        var_data = [headers]
        row_class_colors = []
        for v in merged_variants:
            acmg = v.get("acmg") or {}
            gene = v.get("gene_name") or acmg.get("gene") or "—"
            transcript = v.get("transcript_id") or "—"
            hgvs = v.get("hgvs") or "—"
            consequence = consequence_display_label(v.get("consequence"))
            classification = acmg.get("classification", "Not classified")
            af = acmg.get("gnomad_af")
            af_str = (
                f"{af:.2e}"
                if isinstance(af, (int, float))
                else (acmg.get("gnomad_unavailable_reason") or "N/A")
            )
            var_data.append([gene, transcript, hgvs, consequence, classification, af_str])
            row_class_colors.append(class_colors.get(classification))

        var_table = Table(
            var_data,
            colWidths=[60, 75, 110, 75, 90, 65],
            repeatRows=1,
        )
        var_style_cmds = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2a6ab5")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 7.5),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cccccc")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]
        for i, color in enumerate(row_class_colors, start=1):
            if color:
                var_style_cmds.append(("BACKGROUND", (4, i), (4, i), color))
        var_table.setStyle(TableStyle(var_style_cmds))
        story.append(var_table)
    else:
        story.append(Paragraph("No variants to display.", body_style))

    # ── Footer (drawn on every page: disclaimer, reference genome,
    #    pipeline version, timestamp, Page X of Y) ──

    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=letter,
        topMargin=0.6 * inch,
        bottomMargin=0.8 * inch,
        leftMargin=0.6 * inch,
        rightMargin=0.6 * inch,
        title=f"{pipeline_version} Clinical Report — {sample_id}",
    )

    # "Page X of Y" requires knowing the total page count, which isn't
    # known until the full story is laid out once — the standard
    # ReportLab pattern is a Canvas subclass that buffers pages, then
    # rewrites each page's footer with the final total on save().
    class _NumberedCanvas(reportlab_canvas.Canvas):
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self._saved_page_states = []

        def showPage(self):
            self._saved_page_states.append(dict(self.__dict__))
            self._startPage()

        def save(self):
            total_pages = len(self._saved_page_states)
            for state in self._saved_page_states:
                self.__dict__.update(state)
                self._draw_page_number(total_pages)
                super().showPage()
            super().save()

        def _draw_page_number(self, total_pages):
            self.saveState()
            self.setFont("Helvetica", 6.5)
            self.setFillColorRGB(0.4, 0.4, 0.4)
            self.drawRightString(
                letter[0] - 0.6 * inch,
                0.4 * inch,
                f"Page {self.getPageNumber()} of {total_pages}",
            )
            self.restoreState()

    doc.build(
        story,
        onFirstPage=lambda c, d: _draw_footer_without_page_number(
            c, d, lab_disclaimer, reference_genome, pipeline_version, generated_at
        ),
        onLaterPages=lambda c, d: _draw_footer_without_page_number(
            c, d, lab_disclaimer, reference_genome, pipeline_version, generated_at
        ),
        canvasmaker=_NumberedCanvas,
    )
    logger.info("PDF report rendered via ReportLab: %s", pdf_path)
    return pdf_path


def _draw_footer_without_page_number(
    c, doc_, lab_disclaimer, reference_genome, pipeline_version, generated_at
):
    """Draws the disclaimer/reference/version/timestamp line on every
    page; the "Page X of Y" number itself is drawn separately by
    `_NumberedCanvas._draw_page_number` once the total page count is
    known (see render_clinical_pdf's docstring on why two passes are
    needed)."""
    from reportlab.lib import colors
    from reportlab.lib.units import inch

    c.saveState()
    c.setFont("Helvetica", 6.5)
    c.setFillColor(colors.grey)
    footer_y = 0.4 * inch
    c.drawString(0.6 * inch, footer_y + 16, lab_disclaimer[:150])
    c.drawString(
        0.6 * inch,
        footer_y,
        f"Reference genome: {reference_genome}  |  Pipeline: {pipeline_version}  |  "
        f"Generated: {generated_at}",
    )
    c.restoreState()
