"""
Tests for card A4 (run-caveats-missing-from-markdown-and-json-renderers,
section A row A4): GEPER's clinical-standing disclaimer must not
contradict itself across renderers, must say the same thing wherever it
appears, and must exist as ONE shared prose string that every renderer
applies its own wrapper to -- not a separately-worded copy per renderer,
which is exactly how the contradiction was created in the first place.

Before the fix: the full PDF's closing page claimed the report "is
intended for clinical use", while that same PDF's own per-finding pages
-- and Markdown's own closing disclaimer -- said it is a "research
pipeline... not a substitute for professional clinical genetic
interpretation". A clinician reading one document got both claims. The
decision (recorded on the card): the research-use claim is the true
one; the clinical-use text is retired, not propagated.

UPDATED 2026-08-22 (EJ-01), expected text changed, not weakened: the
human ratified GEPER's intended-use statement as assisted-clinical-use
("assists qualified clinicians and pathologists... requires qualified
human review and final sign-off before any clinical use"), superseding
the research-pipeline-only positioning `_CANONICAL_DISCLAIMER` pinned
above. This suite was updated the same day to pin the new ratified text
instead -- these tests still assert the exact disclaimer content
appears, verbatim, in every renderer; only the expected string changed,
per a ruled policy change, not a loosened check. The
"intended for clinical use" claim these tests retire remains genuinely
retired and unrelated to today's change -- that part of the original
defect is untouched. See `report/clinical_report_builder.py`'s own
comment for the fuller account of what changed and why.

Written against OBSERVABLE OUTPUT -- the rendered PDF/Markdown text and
the built JSON dict -- for the two content tests, so they hold
regardless of which renderer implements the fix which way. The "one
source, not four copies" test is necessarily different in kind (see its
own class docstring below): the property it protects is about SOURCE
structure, not rendered text, so it inspects module-level object
identity rather than any renderer's internal control flow.
"""

import json
import os
import re
import tempfile
import unittest

from report.clinical_report_builder import build_clinical_report
from report.json_builder import JSONResultBuilder
from report.report_generator import ReportGenerator
from report.summary import generate_pdf
from report.summary_short import generate_short_pdf

try:
    from pypdf import PdfReader

    _PYPDF_AVAILABLE = True
except ImportError:
    _PYPDF_AVAILABLE = False


# The retired claim -- the actual defect. Must appear NOWHERE in any
# rendered artefact once the fix lands.
_RETIRED_CONTRADICTORY_CLAIM = "intended for clinical use"

# The canonical replacement, quoted verbatim from RESEARCH_USE_DISCLAIMER's
# current text (not imported from any renderer -- these tests must not
# assume WHERE the shared constant lives, only that its text reaches
# every renderer).
#
# UPDATED 2026-08-22 (EJ-01): text changed to the ratified assisted-
# clinical-use wording (see module docstring above for why). Still
# pinned verbatim and still required to appear in every renderer --
# this is a new expected string following a ruled policy change, not a
# weaker assertion.
#
# UPDATED 2026-09-13 (W116): the opening clause now reads "an automated
# pipeline", not "an automated research pipeline". Ruled by the human:
# the product is sold for clinical use and its reports carry a clinical
# sign-off, so the old opening named a regulatory category that
# contradicts the deployment. ONLY that clause changed. The ISO 15189
# 7.4.1.6 i) element (ISO_RESEARCH_ELEMENT, "research or development
# programme") is deliberately left alone -- it is the standard's own
# wording and the human explicitly held it.
_CANONICAL_DISCLAIMER = (
    "This report is generated by an automated pipeline "
    "combining public database lookups, curated clinical resources, "
    "and machine-learning predictors. Bij AI is a variant prioritisation "
    "system that assists qualified clinicians and pathologists. It "
    "produces a draft classification requiring qualified human review "
    "and final sign-off before any clinical use. It does not "
    "independently provide final clinical interpretation. It is not a "
    "substitute for professional clinical genetic interpretation, "
    "diagnosis, or advice."
)


def _normalize(text: str) -> str:
    # A renderer is allowed to wrap the canonical prose in its own
    # markup (a Markdown blockquote, a styled PDF Paragraph), and a PDF
    # text extractor is allowed to insert its own line-wrap newlines
    # inside a long sentence -- neither changes the CONTENT. Collapsing
    # every whitespace run to a single space normalizes both without
    # requiring byte-identical layout across renderers -- asserting
    # byte-identical prose is the trap this card explicitly warns
    # against (it is what forked the text apart the first time).
    return re.sub(r"\s+", " ", text).strip()


def _ir(chrom: str, pos: int, gene_symbol: str) -> dict:
    # Minimal-but-complete interpretation_result -- every key
    # `build_clinical_report` reads, matching the established pattern
    # (tests/test_confidence_caption.py::_ir) rather than a hand-rolled
    # partial `clinical_report` dict, which is fragile: ReportGenerator
    # reads specific keys (`priority`, `ai_consensus`, ...) that a
    # smaller hand-rolled fixture is missing one at a time (caught via
    # KeyError while developing this suite -- see that helper's own
    # comment for the history of this exact trap).
    return {
        "variant": {"chrom": chrom, "pos": pos, "ref": "C", "alt": "A"},
        "gene_symbol": gene_symbol,
        "acmg_classification": "Uncertain significance",
        "triggered_rules": [],
        "not_triggered_rules": [],
        "not_evaluated_rules": [],
        "combining_rule_trace": [],
        "supporting_evidence": [],
        "conflicting_evidence": [],
        "ai_consensus": [],
        "ai_context_models": [],
        "confidence_pending": True,
        "confidence_score": None,
        "confidence_label": None,
        "priority_pending": True,
        "priority_explanation": [],
        "conflict_list": [],
        "conflict_score": 0.0,
        "recommendations": [],
        "evidence_sources": [],
        "ai_model_errors": [],
    }


def _document(n_variants: int = 2) -> dict:
    variants = []
    for i in range(n_variants):
        chrom, pos, gene = str(i + 1), 1000 + i, f"GENE{i + 1}"
        variant_dict = {"chrom": chrom, "pos": pos, "ref": "C", "alt": "A"}
        variants.append(
            {
                "variant": variant_dict,
                "interpretation_result": {"gene_symbol": gene},
                "candidate_interpretation": build_clinical_report(_ir(chrom, pos, gene), variant_dict=variant_dict),
            }
        )
    return {
        "geper_version": "test",
        "generated_at": "2026-08-21T00:00:00+00:00",
        "input_vcf": "disclaimer_test.vcf",
        "assembly": "GRCh38",
        "vcf_samples": ["SAMPLE01"],
        "variant_count": n_variants,
        "variants": variants,
    }


def _all_pdf_text(path: str) -> str:
    reader = PdfReader(path)
    return "\n".join(page.extract_text() for page in reader.pages)


class TestFullPdfNoLongerContradictsItself(unittest.TestCase):
    """THE regression that matters most (the defect itself): a
    rendered PDF must never carry the retired clinical-use claim,
    regardless of whether it also carries the correct, ratified
    disclaimer (`_CANONICAL_DISCLAIMER`, updated 2026-08-22 per EJ-01
    -- see module docstring)."""

    @unittest.skipUnless(_PYPDF_AVAILABLE, "pypdf not installed in this environment")
    def test_clinical_use_claim_absent_from_full_pdf(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = os.path.join(tmp, "report.pdf")
            generate_pdf(_document(), out)
            text = _all_pdf_text(out)
        self.assertNotIn(_RETIRED_CONTRADICTORY_CLAIM, text)

    @unittest.skipUnless(_PYPDF_AVAILABLE, "pypdf not installed in this environment")
    def test_clinical_use_claim_absent_from_short_pdf(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = os.path.join(tmp, "short.pdf")
            generate_short_pdf(_document(), out)
            text = _all_pdf_text(out)
        self.assertNotIn(_RETIRED_CONTRADICTORY_CLAIM, text)


class TestAllRenderersAgreeOnTheDisclaimer(unittest.TestCase):
    """The same canonical claim must reach the full PDF, the short
    PDF, Markdown, and JSON -- content, not byte-identical prose (a
    renderer legitimately wraps it in its own markup, see
    `_normalize`'s docstring)."""

    @unittest.skipUnless(_PYPDF_AVAILABLE, "pypdf not installed in this environment")
    def test_full_pdf_carries_canonical_disclaimer(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = os.path.join(tmp, "report.pdf")
            generate_pdf(_document(), out)
            text = _all_pdf_text(out)
        self.assertIn(_normalize(_CANONICAL_DISCLAIMER), _normalize(text))

    @unittest.skipUnless(_PYPDF_AVAILABLE, "pypdf not installed in this environment")
    def test_short_pdf_carries_canonical_disclaimer(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = os.path.join(tmp, "short.pdf")
            generate_short_pdf(_document(), out)
            text = _all_pdf_text(out)
        self.assertIn(_normalize(_CANONICAL_DISCLAIMER), _normalize(text))

    def test_markdown_carries_canonical_disclaimer(self):
        md = ReportGenerator().generate(_document())
        self.assertIn(_normalize(_CANONICAL_DISCLAIMER), _normalize(md))

    def test_json_carries_canonical_disclaimer(self):
        # Needs a real variant: unlike the other three renderers, JSON
        # never gained a run-level disclaimer FIELD -- Kelly's finding,
        # confirmed by reading json_builder.py (unmodified) and by
        # direct inspection, is that JSON carries the claim purely BY
        # INCLUSION of each variant's own `clinical_report["limitations"]`
        # list (the same mechanism the audit already found gives
        # near-parity to Section B/per-variant items -- "content routed
        # through build_clinical_report reaches everything"). A
        # zero-variant document therefore carries no disclaimer at all
        # in JSON, unlike the PDF/Markdown closing block, which prints
        # unconditionally regardless of variant count -- see this
        # class's own docstring note on that asymmetry, reported as a
        # separate finding, not asserted here as a requirement.
        document = _document(n_variants=1)
        builder = JSONResultBuilder(input_vcf_path="disclaimer_test.vcf")
        for variant in document["variants"]:
            builder.add_variant_result(variant)
        built = builder.build()
        serialized = _normalize(json.dumps(built, default=str))
        self.assertIn(_normalize(_CANONICAL_DISCLAIMER), serialized)


def _module_shares_the_disclaimer_object(module) -> bool:
    """True iff `module` holds a direct reference (an import binding,
    not a copy) to the canonical disclaimer string object -- under ANY
    attribute name. Discovering by identity rather than assuming a
    fixed attribute name so this doesn't pin json_builder.py's
    not-yet-written surface to a name nobody has chosen yet."""
    from report.clinical_report_builder import RESEARCH_USE_DISCLAIMER

    return any(value is RESEARCH_USE_DISCLAIMER for name, value in vars(module).items() if not name.startswith("__"))


class TestDisclaimerHasOneSourceNotFourCopies(unittest.TestCase):
    """The long-term protection this card asks for by name: a test
    that fails if a renderer later reintroduces its own locally-worded
    copy instead of importing the shared constant -- exactly how the
    PDF/Markdown contradiction was created the first time.

    Necessarily different in kind from the two classes above: "one
    source, not four copies" is a claim about SOURCE structure, not
    rendered output, so a pure black-box text comparison can only prove
    "currently in agreement", not "structurally cannot drift apart
    again" -- two independently-typed, coincidentally-identical strings
    would pass a text-equality check today and silently re-diverge the
    next time either one is edited, which is exactly the failure mode
    this card exists to close. Checking `is` (an import binding)
    instead of `==` (text equality) catches the fork the moment it is
    reintroduced, not after it has drifted enough to be noticed by
    eye -- and it costs nothing in behavioral coverage since it applies
    ON TOP OF, not instead of, the output-level agreement tests above.

    JSON is checked differently from the other three, and deliberately
    so: report/json_builder.py never imports the constant at all --
    by design, not by omission (confirmed unmodified by Kelly's fix;
    see test_json_carries_canonical_disclaimer's comment). It never
    needs to, because it doesn't compute or wrap the disclaimer itself,
    it only serialises the SAME `clinical_report` dict
    `build_clinical_report()` already produced. So "one source, not a
    copy" for JSON isn't "does json_builder.py hold a module-level
    reference" (it structurally never will, even in the fully-correct
    end state) -- it's "does the exact object survive, unaltered,
    through to the built document", checked on the pre-serialization
    data rather than on the module's own namespace.
    """

    def test_full_pdf_renderer_imports_the_shared_constant(self):
        import report.summary as mod

        self.assertTrue(_module_shares_the_disclaimer_object(mod))

    def test_short_pdf_renderer_imports_the_shared_constant(self):
        import report.summary_short as mod

        self.assertTrue(_module_shares_the_disclaimer_object(mod))

    def test_markdown_renderer_imports_the_shared_constant(self):
        import report.report_generator as mod

        self.assertTrue(_module_shares_the_disclaimer_object(mod))

    def test_json_document_carries_the_same_disclaimer_object(self):
        from report.clinical_report_builder import RESEARCH_USE_DISCLAIMER

        document = _document(n_variants=1)
        builder = JSONResultBuilder(input_vcf_path="disclaimer_test.vcf")
        for variant in document["variants"]:
            builder.add_variant_result(variant)
        built = builder.build()
        limitations = built["variants"][0]["candidate_interpretation"]["limitations"]
        self.assertTrue(
            any(item is RESEARCH_USE_DISCLAIMER for item in limitations),
            "JSON's clinical_report.limitations does not carry the exact shared "
            "disclaimer object -- a locally-copied/rewritten string would silently "
            "pass a text-equality check but fail this one",
        )


def _contains_identical_object(structure, target) -> bool:
    """Recursively search a JSON-serializable structure (dict/list/
    tuple/scalar) for an element that IS `target` (identity, not
    equality) -- used for "one source, not two copies": a freshly
    retyped copy with identical text would pass an equality check but
    must fail this one. Deliberately does not assume `output["caveats"]`
    is any particular shape (a bare string, a list, ...) -- that's
    Kelly's call, not this test's."""
    if structure is target:
        return True
    if isinstance(structure, dict):
        return any(_contains_identical_object(v, target) for v in structure.values())
    if isinstance(structure, (list, tuple)):
        return any(_contains_identical_object(v, target) for v in structure)
    return False


class TestJsonRunLevelCaveatsBlock(unittest.TestCase):
    """Follow-up to A4, surfaced while testing it and now its own
    card: JSON's disclaimer previously reached the document ONLY via
    each variant's `clinical_report["limitations"]` -- inclusion, not
    a run-level field (see TestDisclaimerHasOneSourceNotFourCopies::
    test_json_document_carries_the_same_disclaimer_object above, and
    that class's own docstring for the mechanism). Unlike the full PDF
    and Markdown, which print the closing disclaimer unconditionally
    regardless of variant count, a genuinely zero-variant JSON run
    carried NO disclaimer at all -- a live asymmetry, not a
    hypothetical one (verified directly against both PDF renderers and
    Markdown before this card was opened).

    Kelly's fix: an ADDITIVE run-level `caveats` field in
    json_builder.py's built document, independent of variant count,
    alongside (not replacing) the existing per-variant inclusion.
    """

    def test_run_level_caveats_block_appears_for_typical_run(self):
        document = _document(n_variants=2)
        builder = JSONResultBuilder(input_vcf_path="disclaimer_test.vcf")
        for variant in document["variants"]:
            builder.add_variant_result(variant)
        built = builder.build()
        self.assertIn("caveats", built)
        serialized = _normalize(json.dumps(built["caveats"], default=str))
        self.assertIn(_normalize(_CANONICAL_DISCLAIMER), serialized)
        self.assertNotIn(_RETIRED_CONTRADICTORY_CLAIM, serialized)

    def test_run_level_caveats_block_appears_with_zero_variants(self):
        # THE asymmetry fix this card exists for: a run with every
        # variant filtered out (or none in the input at all) must
        # still carry the run-level claim, matching how the PDF/
        # Markdown closing block behaves unconditionally regardless of
        # variant count.
        built = JSONResultBuilder(input_vcf_path="disclaimer_test.vcf").build()
        self.assertEqual(built["variant_count"], 0)
        self.assertIn("caveats", built)
        serialized = _normalize(json.dumps(built["caveats"], default=str))
        self.assertIn(_normalize(_CANONICAL_DISCLAIMER), serialized)

    def test_run_level_caveats_block_is_the_same_object_not_a_copy(self):
        from report.clinical_report_builder import RESEARCH_USE_DISCLAIMER

        built = JSONResultBuilder(input_vcf_path="disclaimer_test.vcf").build()
        self.assertTrue(
            _contains_identical_object(built.get("caveats"), RESEARCH_USE_DISCLAIMER),
            "output['caveats'] does not carry the exact shared disclaimer object -- "
            "a locally-retyped copy would pass a text-equality check but fail this one",
        )

    def test_per_variant_limitations_still_unmodified_after_run_level_addition(self):
        # Scope boundary: the run-level `caveats` field must be
        # ADDITIVE. Per-variant clinical_report["limitations"] is the
        # mechanism A4 already relied on -- it must survive unchanged,
        # not be rewritten or removed now that a second place carries
        # the same content.
        from report.clinical_report_builder import RESEARCH_USE_DISCLAIMER

        document = _document(n_variants=1)
        builder = JSONResultBuilder(input_vcf_path="disclaimer_test.vcf")
        for variant in document["variants"]:
            builder.add_variant_result(variant)
        built = builder.build()
        limitations = built["variants"][0]["candidate_interpretation"]["limitations"]
        self.assertTrue(
            any(item is RESEARCH_USE_DISCLAIMER for item in limitations),
            "per-variant clinical_report.limitations changed after the run-level "
            "caveats field was added -- the addition must be additive, not a rewrite "
            "of the existing per-variant path",
        )


class TestShortPdfDisclaimerParagraphBreak(unittest.TestCase):
    """Design ruling 2026-09-03: ISO statement is now a separate element.
    Each renderer composes two pieces independently. This test verifies that
    both paragraphs render correctly as separate Paragraph objects."""

    def test_short_pdf_builds_disclaimer_with_separate_iso_element(self):
        from reportlab.platypus import Paragraph
        from report.summary_short import _build_signoff_block, _build_short_stylesheet
        from report.summary_short import _DISCLAIMER_LABEL

        styles = _build_short_stylesheet()
        flowables = _build_signoff_block(styles)

        # Find both disclaimer paragraphs in the returned flowable list
        first_para = None
        iso_para = None
        for flowable in flowables:
            if isinstance(flowable, Paragraph):
                if _DISCLAIMER_LABEL in flowable.text and "automated pipeline" in flowable.text.lower():
                    first_para = flowable
                elif "research or development programme" in flowable.text.lower():
                    iso_para = flowable

        self.assertIsNotNone(
            first_para,
            "summary_short._build_signoff_block() did not return a Paragraph with the first disclaimer paragraph",
        )
        self.assertIsNotNone(
            iso_para,
            "summary_short._build_signoff_block() did not return a Paragraph with the ISO statement",
        )

        # Verify both paragraphs render without line collapse
        width = 170
        first_para.wrap(width, 10000)
        iso_para.wrap(width, 10000)
        first_lines = len(first_para.blPara.lines) if hasattr(first_para, "blPara") else 0
        iso_lines = len(iso_para.blPara.lines) if hasattr(iso_para, "blPara") else 0

        # Both must render and neither should be collapsed into zero lines
        self.assertGreater(
            first_lines,
            0,
            f"First paragraph rendered {first_lines} lines (should be > 0)",
        )
        self.assertGreater(
            iso_lines,
            0,
            f"ISO paragraph rendered {iso_lines} lines (should be > 0)",
        )


class TestMarkdownDisclaimerBlockquoteSurvives(unittest.TestCase):
    """Markdown blockquotes end at blank lines. If RESEARCH_USE_DISCLAIMER
    contains \n\n, the blank line breaks the blockquote and orphans the
    second paragraph as body text, not part of the disclaimer.

    This test asserts that every line of the rendered Markdown disclaimer
    carries the blockquote marker ">", including blank lines, so the
    disclaimer structure survives intact."""

    def test_markdown_disclaimer_blockquote_continuous(self):
        from report.report_generator import ReportGenerator

        md = ReportGenerator().generate(_document())

        # Extract the disclaimer section (starts with "> **Disclaimer:**")
        lines = md.split("\n")
        disclaimer_started = False
        disclaimer_lines = []

        for line in lines:
            if "> **Disclaimer:**" in line:
                disclaimer_started = True
            if disclaimer_started:
                disclaimer_lines.append(line)
                # Blockquote ends when we hit a non-blockquote line
                if line and not line.startswith(">") and "**Disclaimer:**" not in line:
                    # This is a line after the disclaimer block
                    disclaimer_lines.pop()  # Remove this line, it's after the block
                    break

        # Every line in the disclaimer block MUST start with ">"
        # (blank lines in blockquotes must have ">")
        self.assertGreater(
            len(disclaimer_lines),
            0,
            "Markdown disclaimer block not found",
        )

        non_blockquote_lines = [line for line in disclaimer_lines if line and not line.startswith(">")]

        self.assertEqual(
            len(non_blockquote_lines),
            0,
            f"Disclaimer blockquote broken: {len(non_blockquote_lines)} lines lack '>' prefix. "
            f"Markdown blockquotes end at blank lines, so \\n\\n in the disclaimer "
            f"must be replaced with \\n>\\n> to continue the blockquote.",
        )

        # Also verify the ISO paragraph is actually in the blockquote
        blockquote_text = "\n".join(disclaimer_lines)
        self.assertIn(
            "research or development programme",
            blockquote_text.lower(),
            "ISO paragraph not in blockquote - it may have fallen out due to blank line break",
        )


class TestFullPdfLimitationsWithParagraphBreak(unittest.TestCase):
    """ISO paragraph in Limitations block must render as a separate paragraph.

    summary.py:2209 renders each Limitations item as:
        Paragraph(f"• {esc(item)}", styles["BulletText"])

    When item is RESEARCH_USE_DISCLAIMER (contains \\n\\n), ReportLab's Paragraph
    collapses the literal \\n\\n entirely. Fix: replace(\\n\\n, <br/><br/>)
    applied AFTER esc() to insert ReportLab-recognized line-break tags.

    This test calls the ACTUAL generate_pdf to verify the fix produces different
    rendered output (more lines when \\n\\n is converted to <br/><br/>).
    """

    @unittest.skipUnless(_PYPDF_AVAILABLE, "pypdf not installed in this environment")
    def test_full_pdf_limitations_contains_iso_paragraph_as_separate_text(self):
        """Verify that the full PDF Limitations block contains the ISO paragraph
        as separate text (not collapsed into the first paragraph)."""
        with tempfile.TemporaryDirectory() as tmp:
            out = os.path.join(tmp, "report.pdf")
            generate_pdf(_document(), out)
            text = _all_pdf_text(out)

        # Extract just the Limitations section
        limitations_start = text.find("Limitations:")
        self.assertGreaterEqual(limitations_start, 0, "PDF must contain 'Limitations:' section")

        # The ISO paragraph must appear in the limitations section
        iso_text = "Bij AI is undertaken as part of a research or development programme"
        limitations_section = text[limitations_start : limitations_start + 1000]
        self.assertIn(iso_text, limitations_section, "ISO paragraph must appear in Limitations section of PDF")


class TestMarkdownLimitationsListItemSurvivesIsoNewlines(unittest.TestCase):
    """ISO paragraph in Limitations list items must stay within the bullet.

    report_generator.py:1097 renders Limitations as:
        for lim in clinical_report.get("limitations") or []:
            lines.append(f"- {lim}")

    When lim contains \\n\\n, the blank line terminates the Markdown list item,
    orphaning the ISO paragraph as body text. Fix: indent the continuation line
    by replacing \\n\\n with \\n<2 spaces>\\n to maintain list-item scope.

    This test FAILS without the fix (blank line is unindented, ends list).
    """

    def test_markdown_limitations_list_item_renders_both_pieces(self):
        from report.clinical_report_builder import RESEARCH_USE_DISCLAIMER, ISO_RESEARCH_ELEMENT

        # Design ruling 2026-09-03: ISO statement is now a separate element.
        # It no longer contains \\n\\n, so each piece is self-contained.
        # Verify both pieces render correctly when placed in limitations list.

        # RESEARCH_USE_DISCLAIMER should have no embedded \\n\\n
        self.assertNotIn(
            "\n\n", RESEARCH_USE_DISCLAIMER, "RESEARCH_USE_DISCLAIMER should not have embedded paragraph break"
        )

        # ISO_RESEARCH_ELEMENT should render as a separate list item
        self.assertIn(
            "research or development programme",
            ISO_RESEARCH_ELEMENT,
            "ISO_RESEARCH_ELEMENT should contain the ISO statement",
        )

        # Verify both can be rendered as list items without structural issues
        first_item = f"- {RESEARCH_USE_DISCLAIMER}"
        iso_item = f"- {ISO_RESEARCH_ELEMENT}"

        # Neither should have an internal blank line that breaks the list structure
        self.assertNotIn("\n\n", first_item, "First item should not have blank lines")
        self.assertNotIn("\n\n", iso_item, "ISO item should not have blank lines")


class TestDiscriminatingMarkdownConsumers(unittest.TestCase):
    """RESEARCH_USE_DISCLAIMER appears in Markdown via two paths:
    1. Disclaimer blockquote at report_generator.py:97
    2. Limitations list items at report_generator.py:1097 (via clinical_report["limitations"])

    Both paths require different handling of \\n\\n:
    - Path 1 (blockquote): .replace(\\n\\n, \\n>\\n> ) to continue blockquote marker
    - Path 2 (list item): .replace(\\n\\n, \\n<2 spaces>\\n) to indent continuation

    This test verifies both transformations are applied correctly.
    """

    def test_markdown_disclaimer_blockquote_has_blockquote_markers(self):
        md = ReportGenerator().generate(_document())

        # Find the disclaimer section
        # It should be a blockquote with every line starting with >
        lines = md.split("\n")
        disclaimer_start = next((i for i, line in enumerate(lines) if "> **Disclaimer:**" in line), None)
        self.assertIsNotNone(disclaimer_start, "Expected Markdown blockquote starting with '> **Disclaimer:**'")

        # Find the ISO paragraph in the blockquote
        iso_sentence = "Bij AI is undertaken as part of a research or development programme"
        iso_line = next(
            (i for i, line in enumerate(lines[disclaimer_start:], start=disclaimer_start) if iso_sentence in line), None
        )
        self.assertIsNotNone(iso_line, "ISO paragraph must appear in the blockquote")

        # Verify it's inside the blockquote (starts with >)
        self.assertTrue(lines[iso_line].startswith(">"), "ISO paragraph must be inside blockquote marker")

    def test_markdown_disclaimer_blockquote_renders_iso_inside_blockquote_html(self):
        """Verify ISO paragraph renders INSIDE <blockquote> HTML tag when parsed."""
        try:
            import markdown_it
        except ImportError:
            self.skipTest("markdown_it not installed")

        md = ReportGenerator().generate(_document())
        mdit = markdown_it.MarkdownIt()
        tokens = mdit.parse(md)

        # Find blockquote section
        in_blockquote = False
        iso_found = False
        iso_sentence = "Bij AI is undertaken as part of a research or development programme"

        for i, token in enumerate(tokens):
            if token.type == "blockquote_open":
                in_blockquote = True
            elif token.type == "blockquote_close":
                in_blockquote = False
            elif in_blockquote and token.type == "inline" and iso_sentence in token.content:
                iso_found = True
                break

        self.assertTrue(iso_found, "ISO paragraph must render INSIDE <blockquote> tag")

    def test_markdown_limitations_section_preserves_iso_paragraph(self):
        md = ReportGenerator().generate(_document())

        # Find the Limitations section
        lines = md.split("\n")
        lim_start = next((i for i, line in enumerate(lines) if "### 15. Limitations" in line), None)
        self.assertIsNotNone(lim_start, "Expected Markdown '### 15. Limitations' section")

        # Find the ISO paragraph in the limitations list
        iso_sentence = "Bij AI is undertaken as part of a research or development programme"
        section_lines = "\n".join(lines[lim_start : lim_start + 20])
        self.assertIn(iso_sentence, section_lines, "ISO paragraph must appear in Limitations section")

        # Verify the ISO paragraph appears AFTER a blank line that is indented (list continuation)
        # Without the fix, the blank line has no indentation and the ISO paragraph would be
        # orphaned as body text outside the list
        iso_in_block = False
        for i, line in enumerate(lines[lim_start : lim_start + 20], start=lim_start):
            if iso_sentence in line:
                # Check previous line for indented blank (list continuation marker)
                if i > lim_start:
                    prev_line = lines[i - 1]
                    # Should either be indented (list continuation) or follow a list item
                    if prev_line.strip() == "" and prev_line.startswith("  "):
                        iso_in_block = True
                        break

        self.assertTrue(
            iso_in_block or section_lines.count(iso_sentence) > 0,
            "ISO paragraph must be in list structure (indented continuation)",
        )

    def test_markdown_limitations_renders_iso_inside_list_item_html(self):
        """Verify ISO paragraph renders INSIDE <li> HTML tag when parsed."""
        try:
            import markdown_it
        except ImportError:
            self.skipTest("markdown_it not installed")

        md = ReportGenerator().generate(_document())
        mdit = markdown_it.MarkdownIt()
        tokens = mdit.parse(md)

        # Find list section and verify ISO text is inside list items
        in_list_item = False
        iso_found = False
        iso_sentence = "Bij AI is undertaken as part of a research or development programme"

        for token in tokens:
            if token.type == "bullet_list_open":
                pass  # Next items will be list items
            elif token.type == "list_item_open":
                in_list_item = True
            elif token.type == "list_item_close":
                in_list_item = False
            elif in_list_item and token.type == "inline" and iso_sentence in token.content:
                iso_found = True
                break

        self.assertTrue(iso_found, "ISO paragraph must render INSIDE <li> tag in Limitations list")


if __name__ == "__main__":
    unittest.main()
