"""
Tests for card A4 (run-caveats-missing-from-markdown-and-json-renderers,
section A row A4): GEPER's clinical-standing disclaimer must not
contradict itself across renderers, must say the same thing wherever it
appears, and must exist as ONE shared prose string that every renderer
applies its own wrapper to -- not a separately-worded copy per renderer,
which is exactly how the contradiction was created in the first place.

Before the fix: the full PDF's closing page claimed the report "is
intended for clinical use", while that same PDF's own per-finding pages
-- and Markdown's own closing disclaimer -- said it is a "research
pipeline... not a substitute for professional clinical genetic
interpretation". A clinician reading one document got both claims. The
decision (recorded on the card): the research-use claim is the true
one; the clinical-use text is retired, not propagated.

Written against OBSERVABLE OUTPUT -- the rendered PDF/Markdown text and
the built JSON dict -- for the two content tests, so they hold
regardless of which renderer implements the fix which way. The "one
source, not four copies" test is necessarily different in kind (see its
own class docstring below): the property it protects is about SOURCE
structure, not rendered text, so it inspects module-level object
identity rather than any renderer's internal control flow.
"""

import json
import os
import re
import tempfile
import unittest

from report.clinical_report_builder import build_clinical_report
from report.json_builder import JSONResultBuilder
from report.report_generator import ReportGenerator
from report.summary import generate_pdf
from report.summary_short import generate_short_pdf

try:
    from pypdf import PdfReader

    _PYPDF_AVAILABLE = True
except ImportError:
    _PYPDF_AVAILABLE = False


# The retired claim -- the actual defect. Must appear NOWHERE in any
# rendered artefact once the fix lands.
_RETIRED_CONTRADICTORY_CLAIM = "intended for clinical use"

# The canonical replacement, quoted verbatim from the card's recorded
# decision (not imported from any renderer -- these tests must not
# assume WHERE the shared constant lives, only that its text reaches
# every renderer).
_CANONICAL_DISCLAIMER = (
    "This report is generated by an automated research pipeline "
    "combining public database lookups, curated clinical resources, "
    "and machine-learning predictors. It is not a substitute for "
    "professional clinical genetic interpretation, diagnosis, or "
    "advice. All findings should be reviewed and confirmed by a "
    "qualified clinical geneticist or genetic counselor before any "
    "medical decision is made; clinical decisions must not be based "
    "solely on this report."
)


def _normalize(text: str) -> str:
    # A renderer is allowed to wrap the canonical prose in its own
    # markup (a Markdown blockquote, a styled PDF Paragraph), and a PDF
    # text extractor is allowed to insert its own line-wrap newlines
    # inside a long sentence -- neither changes the CONTENT. Collapsing
    # every whitespace run to a single space normalizes both without
    # requiring byte-identical layout across renderers -- asserting
    # byte-identical prose is the trap this card explicitly warns
    # against (it is what forked the text apart the first time).
    return re.sub(r"\s+", " ", text).strip()


def _ir(chrom: str, pos: int, gene_symbol: str) -> dict:
    # Minimal-but-complete interpretation_result -- every key
    # `build_clinical_report` reads, matching the established pattern
    # (tests/test_confidence_caption.py::_ir) rather than a hand-rolled
    # partial `clinical_report` dict, which is fragile: ReportGenerator
    # reads specific keys (`priority`, `ai_consensus`, ...) that a
    # smaller hand-rolled fixture is missing one at a time (caught via
    # KeyError while developing this suite -- see that helper's own
    # comment for the history of this exact trap).
    return {
        "variant": {"chrom": chrom, "pos": pos, "ref": "C", "alt": "A"},
        "gene_symbol": gene_symbol,
        "acmg_classification": "Uncertain significance",
        "triggered_rules": [],
        "not_triggered_rules": [],
        "not_evaluated_rules": [],
        "combining_rule_trace": [],
        "supporting_evidence": [],
        "conflicting_evidence": [],
        "ai_consensus": [],
        "ai_context_models": [],
        "confidence_pending": True,
        "confidence_score": None,
        "confidence_label": None,
        "priority_pending": True,
        "priority_explanation": [],
        "conflict_list": [],
        "conflict_score": 0.0,
        "recommendations": [],
        "evidence_sources": [],
        "ai_model_errors": [],
    }


def _document(n_variants: int = 2) -> dict:
    variants = []
    for i in range(n_variants):
        chrom, pos, gene = str(i + 1), 1000 + i, f"GENE{i + 1}"
        variant_dict = {"chrom": chrom, "pos": pos, "ref": "C", "alt": "A"}
        variants.append(
            {
                "variant": variant_dict,
                "interpretation_result": {"gene_symbol": gene},
                "clinical_report": build_clinical_report(_ir(chrom, pos, gene), variant_dict=variant_dict),
            }
        )
    return {
        "geper_version": "test",
        "generated_at": "2026-08-21T00:00:00+00:00",
        "input_vcf": "disclaimer_test.vcf",
        "assembly": "GRCh38",
        "vcf_samples": ["SAMPLE01"],
        "variant_count": n_variants,
        "variants": variants,
    }


def _all_pdf_text(path: str) -> str:
    reader = PdfReader(path)
    return "\n".join(page.extract_text() for page in reader.pages)


class TestFullPdfNoLongerContradictsItself(unittest.TestCase):
    """THE regression that matters most (the defect itself): a
    rendered PDF must never carry the retired clinical-use claim,
    regardless of whether it also carries the correct research-use
    one."""

    @unittest.skipUnless(_PYPDF_AVAILABLE, "pypdf not installed in this environment")
    def test_clinical_use_claim_absent_from_full_pdf(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = os.path.join(tmp, "report.pdf")
            generate_pdf(_document(), out)
            text = _all_pdf_text(out)
        self.assertNotIn(_RETIRED_CONTRADICTORY_CLAIM, text)

    @unittest.skipUnless(_PYPDF_AVAILABLE, "pypdf not installed in this environment")
    def test_clinical_use_claim_absent_from_short_pdf(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = os.path.join(tmp, "short.pdf")
            generate_short_pdf(_document(), out)
            text = _all_pdf_text(out)
        self.assertNotIn(_RETIRED_CONTRADICTORY_CLAIM, text)


class TestAllRenderersAgreeOnTheDisclaimer(unittest.TestCase):
    """The same canonical claim must reach the full PDF, the short
    PDF, Markdown, and JSON -- content, not byte-identical prose (a
    renderer legitimately wraps it in its own markup, see
    `_normalize`'s docstring)."""

    @unittest.skipUnless(_PYPDF_AVAILABLE, "pypdf not installed in this environment")
    def test_full_pdf_carries_canonical_disclaimer(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = os.path.join(tmp, "report.pdf")
            generate_pdf(_document(), out)
            text = _all_pdf_text(out)
        self.assertIn(_normalize(_CANONICAL_DISCLAIMER), _normalize(text))

    @unittest.skipUnless(_PYPDF_AVAILABLE, "pypdf not installed in this environment")
    def test_short_pdf_carries_canonical_disclaimer(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = os.path.join(tmp, "short.pdf")
            generate_short_pdf(_document(), out)
            text = _all_pdf_text(out)
        self.assertIn(_normalize(_CANONICAL_DISCLAIMER), _normalize(text))

    def test_markdown_carries_canonical_disclaimer(self):
        md = ReportGenerator().generate(_document())
        self.assertIn(_normalize(_CANONICAL_DISCLAIMER), _normalize(md))

    def test_json_carries_canonical_disclaimer(self):
        # Needs a real variant: unlike the other three renderers, JSON
        # never gained a run-level disclaimer FIELD -- Kelly's finding,
        # confirmed by reading json_builder.py (unmodified) and by
        # direct inspection, is that JSON carries the claim purely BY
        # INCLUSION of each variant's own `clinical_report["limitations"]`
        # list (the same mechanism the audit already found gives
        # near-parity to Section B/per-variant items -- "content routed
        # through build_clinical_report reaches everything"). A
        # zero-variant document therefore carries no disclaimer at all
        # in JSON, unlike the PDF/Markdown closing block, which prints
        # unconditionally regardless of variant count -- see this
        # class's own docstring note on that asymmetry, reported as a
        # separate finding, not asserted here as a requirement.
        document = _document(n_variants=1)
        builder = JSONResultBuilder(input_vcf_path="disclaimer_test.vcf")
        for variant in document["variants"]:
            builder.add_variant_result(variant)
        built = builder.build()
        serialized = _normalize(json.dumps(built, default=str))
        self.assertIn(_normalize(_CANONICAL_DISCLAIMER), serialized)


def _module_shares_the_disclaimer_object(module) -> bool:
    """True iff `module` holds a direct reference (an import binding,
    not a copy) to the canonical disclaimer string object -- under ANY
    attribute name. Discovering by identity rather than assuming a
    fixed attribute name so this doesn't pin json_builder.py's
    not-yet-written surface to a name nobody has chosen yet."""
    from report.clinical_report_builder import RESEARCH_USE_DISCLAIMER

    return any(value is RESEARCH_USE_DISCLAIMER for name, value in vars(module).items() if not name.startswith("__"))


class TestDisclaimerHasOneSourceNotFourCopies(unittest.TestCase):
    """The long-term protection this card asks for by name: a test
    that fails if a renderer later reintroduces its own locally-worded
    copy instead of importing the shared constant -- exactly how the
    PDF/Markdown contradiction was created the first time.

    Necessarily different in kind from the two classes above: "one
    source, not four copies" is a claim about SOURCE structure, not
    rendered output, so a pure black-box text comparison can only prove
    "currently in agreement", not "structurally cannot drift apart
    again" -- two independently-typed, coincidentally-identical strings
    would pass a text-equality check today and silently re-diverge the
    next time either one is edited, which is exactly the failure mode
    this card exists to close. Checking `is` (an import binding)
    instead of `==` (text equality) catches the fork the moment it is
    reintroduced, not after it has drifted enough to be noticed by
    eye -- and it costs nothing in behavioral coverage since it applies
    ON TOP OF, not instead of, the output-level agreement tests above.

    JSON is checked differently from the other three, and deliberately
    so: report/json_builder.py never imports the constant at all --
    by design, not by omission (confirmed unmodified by Kelly's fix;
    see test_json_carries_canonical_disclaimer's comment). It never
    needs to, because it doesn't compute or wrap the disclaimer itself,
    it only serialises the SAME `clinical_report` dict
    `build_clinical_report()` already produced. So "one source, not a
    copy" for JSON isn't "does json_builder.py hold a module-level
    reference" (it structurally never will, even in the fully-correct
    end state) -- it's "does the exact object survive, unaltered,
    through to the built document", checked on the pre-serialization
    data rather than on the module's own namespace.
    """

    def test_full_pdf_renderer_imports_the_shared_constant(self):
        import report.summary as mod

        self.assertTrue(_module_shares_the_disclaimer_object(mod))

    def test_short_pdf_renderer_imports_the_shared_constant(self):
        import report.summary_short as mod

        self.assertTrue(_module_shares_the_disclaimer_object(mod))

    def test_markdown_renderer_imports_the_shared_constant(self):
        import report.report_generator as mod

        self.assertTrue(_module_shares_the_disclaimer_object(mod))

    def test_json_document_carries_the_same_disclaimer_object(self):
        from report.clinical_report_builder import RESEARCH_USE_DISCLAIMER

        document = _document(n_variants=1)
        builder = JSONResultBuilder(input_vcf_path="disclaimer_test.vcf")
        for variant in document["variants"]:
            builder.add_variant_result(variant)
        built = builder.build()
        limitations = built["variants"][0]["clinical_report"]["limitations"]
        self.assertTrue(
            any(item is RESEARCH_USE_DISCLAIMER for item in limitations),
            "JSON's clinical_report.limitations does not carry the exact shared "
            "disclaimer object -- a locally-copied/rewritten string would silently "
            "pass a text-equality check but fail this one",
        )


if __name__ == "__main__":
    unittest.main()
