name: pytest

on:
  push:
  pull_request:

jobs:
  geper-tests:
    name: geper/ pytest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: geper
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: geper/requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: python -m pytest tests/ -v

  kim_pipeline-tests:
    name: kim_pipeline/ pytest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kim_pipeline
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: kim_pipeline/requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: python -m pytest tests/ -v
